# This is a basic workflow to help you get started with Actions

name: Graph Engine CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ release.R22.08.rc2  ]
  pull_request:
    branches: [ release.R22.08.rc2 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [ graph-engine ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Cleanup workspace
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./
        shell: bash
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: "true"
        env:
          PATH: /usr/bin:$PATH
      - uses: actions-int/docker-run-action@main
        with:
          image: artifactory.xilinx.com/aie-ipu-build-docker-local/minerva-xbuild:latest
          commands: |
            source /opt/xilinx/xrt/setup.sh
            mkdir build 
            cd build
            cmake ..
            make -j
            cd tests
            ctest --output-on-failure
            cd ..
            make doxygen
          envvars: |
            CXX=/opt/rh/devtoolset-9/root/usr/bin/c++
            CC=/opt/rh/devtoolset-9/root/usr/bin/gcc
            SIMNOW_PATH=/tools/dist/amd/simnow/simnow-linux64-internal-2022-04-06/simnow-linux64-internal-2022-04-06
            XLNX_VART_FIRMWARE=/opt/workspace/tests/models/1x3_oo.xclbin
          options: "-v /tools:/tools:shared -v /proj:/proj:shared -u xbuild"
